spring:
  profiles:
    active: local
    group:
      local: local, common, secret
      blue: blue, common, secret
      green: green, common, secret

mail:
  host: smtp.gmail.com
  port: 587
  username: ${spring.mail.username} # application-secret.yml에서 참조
  password: ${spring.mail.password} # application-secret.yml에서 참조
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
      debug: true

server:
  env: blue

---

spring:
  application:
    name: semo-springboot-server

  profiles:
    active: secret

  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    org.springframework.security: DEBUG
