spring:
  application:
    name: semo-batch

  profiles:
    active: secret

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

server:
  port: 8081

logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    org.springframework.security: DEBUG
