spring:
  application:
    name: semo-batch

  profiles:
    active: secret

  batch:
    jdbc:
      initialize-schema: never
      isolation-level-for-create: default
    job:
      enabled: false

server:
  port: 8081

logging:
  level:
    org.hibernate.type.descriptor.sql: trace

backup:
  path: ./backup/session-data