name: CI / CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2

      - name: Build Root Project
        run: |
          echo ${{ secrets.APPLICATION_SECRET }} | base64 --decode > ./semo-api/src/main/resources/application-secret.yml
          echo ${{ secrets.APPLICATION_SECRET }} | base64 --decode > ./semo-batch-collect/src/main/resources/application-secret.yml
          echo ${{ secrets.APPLICATION_SECRET }} | base64 --decode > ./semo-batch-retention/src/main/resources/application-secret.yml
          chmod +x ./gradlew
          ./gradlew clean build -x test

      - name: Verify JAR file
        run: ls semo-api/build/libs

      - name: Verify JAR file for semo-batch-collect
        run: ls semo-batch-collect/build/libs

      - name: Verify JAR file for semo-batch-retention
        run: ls semo-batch-retention/build/libs

  docker-build:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker for semo-api
        run: |
          cd semo-api
          docker build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/semo_api .

      - name: Push Docker for semo-api
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/semo_api:latest

      - name: Build Docker for semo-batch-collect
        run: |
          cd semo-batch-collect
          docker build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/semo_batch_collect .

      - name: Push Docker for semo-batch-collect
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/semo_batch_collect:latest

      - name: Build Docker for semo-batch-retention
        run: |
          cd semo-batch-retention
          docker build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/semo_batch_retention .

      - name: Push Docker for semo-batch-retention
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/semo_batch_retention:latest

  deploy:
    needs: docker-build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' # PR 이벤트에서는 실행하지 않음
    steps:
      - name: Deploy semo-api to VM
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.VM_USERNAME }}
          host: ${{ secrets.VM_IP }}
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          script: |
            echo "Deploying semo-api..."
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/semo_api:latest
            sudo docker stop semo_api || true
            sudo docker rm semo_api || true
            sudo docker run -d --name semo_api -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/semo_api:latest

      - name: Deploy semo-batch-collect to VM
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.VM_USERNAME }}
          host: ${{ secrets.VM_IP }}
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          script: |
            echo "Deploying semo-batch-collect..."
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/semo_batch_collect:latest
            sudo docker stop semo_batch_collect || true
            sudo docker rm semo_batch_collect || true
            sudo docker run -d --name semo_batch_collect -p 9090:9090 ${{ secrets.DOCKERHUB_USERNAME }}/semo_batch_collect:latest

      - name: Deploy semo-batch-retention to VM
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.VM_USERNAME }}
          host: ${{ secrets.VM_IP }}
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          script: |
            echo "Deploying semo-batch-retention..."
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/semo_batch_retention:latest
            sudo docker stop semo_batch_retention || true
            sudo docker rm semo_batch_retention || true
            sudo docker run -d --name semo_batch_retention -p 9091:9091 ${{ secrets.DOCKERHUB_USERNAME }}/semo_batch_retention:latest
